### ISSUE TITLE
Add logo to readMe

### ISSUE THREAD

**Issue by hbrandon15** [hbrandon15/first-geneers-podcast#1]
```
<!-- TODO: Add logo to readMe -->
```

https://github.com/hbrandon15/first-geneers-podcast/blob/5cd5ade11e35bf3eaf1194c1228e8eaacef32c4a/README.md#L4

**Comment by logicbyjoel** [comment]
Logo has been added to ReadMe

**Comment by logicbyjoel** [comment]
Pending approval... by @hbrandon15

**Comment by hbrandon15** [comment]
Sweet! Looking good!!
