### ISSUE TITLE
Insert latest Bootstrap CDN link reference here -->

### ISSUE THREAD

**Issue by hbrandon15** [hbrandon15/first-geneers-podcast#6]
```
    <!-- TODO: Insert latest Bootstrap CDN link reference here -->
```

https://github.com/hbrandon15/first-geneers-podcast/blob/bc2dd1aaca8846bd418663d7c082eacad29f9893/index.html#L11

**Comment by logicbyjoel** [comment]
Done. NOTE: Bootstrap rules seem to conflict with our local css stylesheet. Do we have a style guide to use for this project?
